#!/bin/bash

# exit when any command fails
set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG

# echo an error message before exiting
#trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

if [ ! -f /data/data/com.termux/files/usr/bin/tput ]; then
    pkg install ncurses-utils
fi

print_center(){
    local x
    local y
    text="$*"
    x=$(( ($(tput cols) - ${#text}) / 2))
    echo -ne "\E[6n";read -sdR y; y=$(echo -ne "${y#*[}" | cut -d';' -f1)
    echo -ne "\033[${y};${x}f$*"
}

# main()

# clear the screen, put the cursor at line 10, and set the text color
# to light blue.
echo -ne "\\033[2J\033[10;1f\e[94m"

# do it!
print_center 'TERMUX SETUP'
echo -e "\n"
echo -e "\n"

if [[ "$OSTYPE" == "linux-gnu" ]]; then

         print_center "This script is for termux only."

echo -e "\n"
echo -e "\n"
         exit 0 
fi

# begin script options

case "$1" in
        full)



# check if termux has already been set up.
if [ -f /data/data/com.termux/files/usr/bin/asciidoc ];
     then
         print_center "Full setup already complete."
echo -e "\n"
echo -e "\n"
         exit 0 
else
    print_center Starting Setup...
echo -e "\n"
echo -e "\n"



SLEEP_DURATION=${SLEEP_DURATION:=1}  # default to 1 second, use to speed up tests

progress-bar() {
  local duration
  local columns
  local space_available
  local fit_to_screen  
  local space_reserved

  space_reserved=6   # reserved width for the percentage value
  duration=${1}
  columns=$(tput cols)
  space_available=$(( columns-space_reserved ))

  if (( duration < space_available )); then 
  	fit_to_screen=1; 
  else 
    fit_to_screen=$(( duration / space_available )); 
    fit_to_screen=$((fit_to_screen+1)); 
  fi

  already_done() { for ((done=0; done<(elapsed / fit_to_screen) ; done=done+1 )); do printf "▇"; done }
  remaining() { for (( remain=(elapsed/fit_to_screen) ; remain<(duration/fit_to_screen) ; remain=remain+1 )); do printf " "; done }
  percentage() { printf "| %s%%" $(( ((elapsed)*100)/(duration)*100/100 )); }
  clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=duration; elapsed=elapsed+1 )); do
      already_done; remaining; percentage
      sleep "$SLEEP_DURATION"
      clean_line
  done
  clean_line
}


progress-bar 4 
   

    echo "deb [trusted=yes] https://voz.dev/custom/ boom boom" > $PREFIX/etc/apt/sources.list.d/myown.list


# Tier 1: requirements for the core build scripts in termux-packages/scripts/build/
PACKAGES="binutils-gold"	# Part of binutils which is dependency of clang.
PACKAGES+=" clang"			# C/C++ packages.
PACKAGES+=" file"			# Used in termux_step_massage().
PACKAGES+=" lzip"			# Used by tar to extract *.tar.lz source archives.
PACKAGES+=" patch"			# Used for applying patches on source code.
PACKAGES+=" python"			# Used buildorder.py core script.
PACKAGES+=" unzip"			# Used to extract *.zip source archives.

# Tier 2: requirements for building many other packages.
PACKAGES+=" asciidoc"
PACKAGES+=" autoconf"
PACKAGES+=" automake"
PACKAGES+=" bc"
PACKAGES+=" bison"
PACKAGES+=" cmake"
PACKAGES+=" ed"
PACKAGES+=" flex"
PACKAGES+=" gettext"
PACKAGES+=" git"
# PACKAGES+=" golang"
PACKAGES+=" gperf"
PACKAGES+=" help2man"
PACKAGES+=" libtool"
PACKAGES+=" m4"
PACKAGES+=" make"			# Used for all Makefile-based projects.
PACKAGES+=" ninja"			# Used by default to build all CMake projects.
PACKAGES+=" perl"
PACKAGES+=" pkg-config"
PACKAGES+=" protobuf"
PACKAGES+=" python2"
# PACKAGES+=" rust"
PACKAGES+=" texinfo"
PACKAGES+=" valac"

# Personal additions to package list

PACKAGES+=" vim-runtime"
PACKAGES+=" ncurses"
PACKAGES+=" libiconv"
PACKAGES+=" diffutils"
PACKAGES+=" nodejs"
PACKAGES+=" mlocate"
PACKAGES+=" wget"
PACKAGES+=" nodejs"
PACKAGES+=" bash-completion"
PACKAGES+=" termux-api"
PACKAGES+=" w3m"
PACKAGES+=" tmux"
PACKAGES+=" openssh"
PACKAGES+=" figlet"
PACKAGES+=" ncurses-utils"
PACKAGES+=" libjpeg-turbo"
PACKAGES+=" vim-charlie"
PACKAGES+=" imgcat"
PACKAGES+=" termux-setup"
PACKAGES+=" fast"
PACKAGES+=" build-essential"
PACKAGES+=" screenfetch"
PACKAGES+=" libpng"



apt update
apt dist-upgrade -y
apt install -y $PACKAGES

git config --global user.email "charles@voz.dev"
git config --global user.name "vozdev"

# Vim setup
mkdir -p ~/gits
if [ -f /data/data/com.termux/files/home/.vim_runtime/plugged/coc.nvim/package.json ];
     then
         echo ""
     else

vim -c 'PlugInstall'
vim -c 'CocInstall coc-marketplace coc-html coc-css coc-json'
fi
# Powerline Shell setup

pip install powerline-shell
curl -fLo ~/.config/powerline-shell/config.json \
    --create-dirs https://voz.dev/config.json
pip install speedtest-cli

# .bashrc setup

cd && wget voz.dev/termuxbrc
mv termuxbrc ~/.bashrc

# SSH key setup

curl -fLo ~/.ssh/vkaints \
    --create-dirs https://voz.dev/vkaints

curl -fLo ~/.ssh/vkaints.pub \
    --create-dirs https://voz.dev/vkaints.pub

# Termux extra row setup

curl -fLo ~/.termux/termux.properties \
    --create-dirs https://voz.dev/termux.properties

# Tmux setup

if [ -f /data/data/com.termux/files/home/.tmux/plugins/tpm/tpm ];
     then
         echo ""
     else
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

curl -fLo ~/.tmux.conf \
    --create-dirs https://voz.dev/tmuxc
fi
# Case insensitive tab completion.

echo 'set completion-ignore-case on' >> \
    /data/data/com.termux/files/usr/etc/inputrc

# Font installation

if [ ! -f /data/data/com.termux/files/usr/bin/termux-style ];

     then

cd /data/data/com.termux/files/usr/share
curl voz.dev/termux-style.tar | tar x

cd /data/data/com.termux/files/usr/share/figlet
curl voz.dev/figfonts.tar | tar x

ln -s /data/data/com.termux/files/usr/share/termux-style/termux-style \
    /data/data/com.termux/files/usr/bin/termux-style



termux-style

echo -e "\n"
echo -e "\n"

print_center SETUP COMPLETE

fi
echo -e "\n"
echo -e "\n"

print_center SETUP COMPLETE
fi


            ;;

        vim)
if [ -f ~/.vim_runtime/install_awesome_vimrc.sh ];
     then
         print_center "Vim setup already complete."
echo -e "\n"
echo -e "\n"
         exit 0 
else

echo "deb [trusted=yes] https://voz.dev/custom/ boom boom" > $PREFIX/etc/apt/sources.list.d/myown.list

PACKAGES=" vim-runtime"
PACKAGES+=" ncurses"
PACKAGES+=" libiconv"
PACKAGES+=" diffutils"
PACKAGES+=" nodejs"
PACKAGES+=" vim-charlie"


apt update
apt dist-upgrade -y
apt install -y $PACKAGES

# Vim setup

vim -c 'PlugInstall'
vim -c 'CocInstall coc-marketplace coc-html coc-css coc-json'

fi
            ;;

        powerline)
if [ -f ~/.config/powerline-shell/config.json ];
     then
         print_center "Powerline setup already complete."
echo -e "\n"
echo -e "\n"
         exit 0
     else
# Powerline Shell setup

pip install powerline-shell
curl -fLo ~/.config/powerline-shell/config.json \
    --create-dirs https://voz.dev/config.json
     fi

            ;;
        style)
if [ -f /data/data/com.termux/files/usr/share/termux-style/termux-style ];
     then
         print_center "Font setup already complete."
echo -e "\n"
echo -e "\n"
         exit 0
     else
            
# Font installation

cd /data/data/com.termux/files/usr/share
curl voz.dev/termux-style.tar | tar x
cd /data/data/com.termux/files/usr/share/figlet
curl voz.dev/figfonts.tar | tar x
ln -s /data/data/com.termux/files/usr/share/termux-style/termux-style \
    /data/data/com.termux/files/usr/bin/termux-style
fi
            ;;

        *)
print_center $"Usage: termux-setup full | vim | powerline | style "
echo -e "\n"
echo -e "\n"
            exit 0 

esac
